---

- pip:
    name: docker

- name: get latest docker images
  docker_image:
    name: "{{ item }}:latest"
    state: present
    pull: yes
  with_items:
    - selenium/hub
    - selenium/node-chrome
    - selenium/node-firefox
